DROP TABLE IF EXISTS admin;

CREATE TABLE IF NOT EXISTS admin (
    id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ,
    nome TEXT NOT NULL ,
    email TEXT NOT NULL UNIQUE ,
    password TEXT NOT NULL
)
